### ISSUE TITLE
Investigate Xsens filter scenarios

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#191]
We think we might be using the scenario which ignores the magnetic field.

- [x] Figure out which scenario it is using.
- [x] Decide which one we want to be the default (Low_mag_dep?)
- [x] If necessary, modify the ROS driver code to set the scenario when it starts.

**Comment by takluyver** [comment]
We found it was using one called `north_reference`. We have set it to `general`. Waiting to test it.

**Comment by takluyver** [comment]
Progress: it no longer uses a fixed heading when you start it up. The headings still weren't right, though. We'll try doing a new MFM next time.

**Comment by takluyver** [comment]
@tsaoyu I realised last night that the bad readings we were getting in our final outdoor test might be partly due to the 180 degrees 'correction' we put into the sensor_service_imu code on Saturday. If you're testing at the weekend, try taking that out again.

**Comment by tsaoyu** [comment]
Good point. I assume that is the downside of the hardcode approach. 
I will look at that 🔨  during weekend.

**Comment by tsaoyu** [comment]
Progress: a consistent heading reading is acquired with `north_reference` is as profile, `NED` framework with 90 degrees offset. Drift in heading still happens may because the calibration or slight move during the start up.

**Comment by takluyver** [comment]
We're still not reliably getting the right numbers from this. Do we:

1. Carry on fiddling with the settings of the Xsens
2. Go back to the settings which reliably produced a number relative to the starting heading, and accept that we can only start that node with the boat on land.
3. Revert to using the MinIMU for now

**Comment by joshctaylor** [comment]
Did you try talking to Monica at xSens? She's been the most useful when I had sensor issues. I found the best was was to call them.

**Comment by takluyver** [comment]
Thanks Josh! Tony, do you have the necessary contact information?

**Comment by joshctaylor** [comment]
Monique Paulich <Monique.Paulich@xsens.com>
+31 88 97367 00

If you are using the university phones use the following access number
to allow you to dial internationally

0843 375 1020 (Planet Talk)

**Comment by tsaoyu** [comment]
After bit research on the technical issue, I managed to make Xsens give us consistent heading reference now. As a reference I put some important points here

1. Do not use Active Heading Stabilisation (AHS) even it sounds like the thing we are looking. What it is actually doing is to use a stable magnetic field as a reference to correct gyro bias. Because of this, once it is actively no matter which profile is used, all heading reads out are not magnetic filed referenced any more. 

2. Rule of thumb for the calibration: at least 3 minutes will sufficiently large angle covered and held it **really** still. No Gaussian distributed normalised magnetic residual means we are in trouble, those calibrations should be discarded and should be use for the missions.

3. Orientation rest are set of  tool that help us to realign IMU inside the boat. It works like this: reset heading (means align x axis to north), inclination(align tangle plane), and alignment (x axis align with the centre of boat). The store option will remember those setting and write it to sensor. We don't need to touch because we currently hard code the rotation in `imu_service` node now.

4. Another dangerous thing we shouldn't click is a little compass with save icon. This is for in run calibration (ICC) function, which assume the full calibration is not possible and click such bottom will write a new magnetic field matrix to the sensor. 

5. Move the system during no rotation period will result in a wrong gyroscope bias calibration which leads to a slow but bounded drift on the heading. We need to hold the boat still for at least 6 seconds when launching the system. 

6. Position of battery has a huge influence on the magnetic field, firmly attach battery at exact place on top of RPi otherwise an unbounded drift on heading will happen.

**Comment by tsaoyu** [comment]
Attach screen shot of a successful calibration. 
![screenshot from 2017-08-26 00-27-23](https://user-images.githubusercontent.com/6488896/29736018-625c4520-89f5-11e7-8df0-144d1525429e.png)

**Comment by takluyver** [comment]
Nice! Was that calibration with the raspi and the battery pack present?

**Comment by tsaoyu** [comment]
No, this one was done without the presence of battery pack.
but the one with battery pack looks pretty same with this.
